Update apk.yml

diff --git a/.github/workflows/apk.yml b/.github/workflows/apk.yml
--- a/.github/workflows/apk.yml
+++ b/.github/workflows/apk.yml
@@ -65,15 +65,18 @@ jobs:
           path: ${{ env.main_project_module }}/build/outputs/apk/debug/
 
       - name: Decode Keystore
-        env:
-          SIGNING_KEYSTORE_FILE: ${{ secrets.KEYSTORE_BASE64 }}
         run: |
-          echo "$SIGNING_KEYSTORE_FILE" | base64 -d > ${{ secrets.KEYSTORE }}
-          ls -alh ${{ secrets.KEYSTORE }}
+          if [[ -z "${{ secrets.KEYSTORE_BASE64 }}" ]]; then
+            echo "ERROR: KEYSTORE_BASE64 is UNDEFINED!" >&2
+            exit 1
+          fi
+
+          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > "$RUNNER_TEMP/keystore.jks"
+          ls -alh "$RUNNER_TEMP/keystore.jks"
 
       - name: Build Release APK
         env:
-          KEYSTORE: ${{ secrets.KEYSTORE }}
+          KEYSTORE: $RUNNER_TEMP/keystore.jks
           KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
           KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
           STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
